// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	CategoryID          int32     `gorm:"column:category_id;primaryKey;autoIncrement:true" json:"category_id"`
	CategoryName        string    `gorm:"column:category_name" json:"category_name"`
	CategoryDescription string    `gorm:"column:category_description" json:"category_description"`
	CreatedAt           time.Time `gorm:"column:created_at;not null;default:current_timestamp()" json:"created_at"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
