// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameProduct = "product"

// Product mapped from table <product>
type Product struct {
	ProductID          int32          `gorm:"column:product_id;primaryKey;autoIncrement:true" json:"product_id"`
	ProductName        string         `gorm:"column:product_name" json:"product_name"`
	ProductDescription string         `gorm:"column:product_description" json:"product_description"`
	Stock              int32          `gorm:"column:stock" json:"stock"`
	ProductPrice       float64        `gorm:"column:product_price" json:"product_price"`
	Status             string         `gorm:"column:status" json:"status"`
	CategoryID         int32          `gorm:"column:category_id" json:"category_id"`
	CreatedAt          time.Time      `gorm:"column:created_at;not null;default:current_timestamp()" json:"created_at"`
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at;not null" json:"deleted_at"`
	UpdatedAt          time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
