# listen addr of http api server
addr = ":8000"

# [owner]
name = "Samu Chakraborty"
dob = 1997-12-10T07:32:00-08:00 # First class dates? Why not?

# [database]
server = "127.0.0.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true
