output   = "../models"
wipe     = true
no-tests = true
add-enum-types = true

[mysql]
dbname = "inventory"
host = "localhost"
port = 3306
user = "root"
pass = "new_password"
sslmode = "false"
blacklist = ["migrations", "other", "schema_migrations"]
