definitions:
  model.User:
    properties:
      role:
        type: string
      username:
        type: string
    type: object
  utils.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message: {}
    type: object
info:
  contact: {}
paths:
  /v1/createUser:
    post:
      consumes:
      - application/json
      description: Create User
      parameters:
      - description: Object
        in: body
        name: Object
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Create User
      tags:
      - User
  /v1/getAllUser:
    get:
      consumes:
      - application/json
      description: get User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HTTPError'
      summary: List User
      tags:
      - User
swagger: "2.0"
